# -*- coding: utf-8 -*-

"""scrape-inspirational-quotes01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EbIHA6LyujTAA4voEBaz6vC_Z6UNGq6E
"""

#description:  scrape inspiring quotes using python
import pandas as pd
import requests
import urllib.request 
import pdfplumber

# create lists
authors = []
quotes = []



#create new function for site scrape
def scrape_website(pagenumber):
  page_num = str(pagenumber)
  url = 'https://www.goodreads.com/quotes/tag/inspirational-quotes?page=' + page_num 
  webpage = requests.get(url)
  soup = BeautifulSoup(webpage.text, 'html.parser')
  quotetext = soup.find_all('div', attrs = {'class':'quoteText'})

  for i in quotetext:
    quote = i.text.strip().split('\n')[0]
    author = i.find('span', attrs={'class':'authorOrTitle'}).text.strip()
    quotes.append(quote)
    authors.append(author)

# loop through n pages
n = 45
for num in range(40, n):
  scrape_website(num)

#combine the lists
combine_list = []
for i in range(len(quotes)):
  combine_list.append(quotes[i]+' - '+authors[i])

combine_list

